lan: fr # source language
target_languages:
  - en
  - de
  - uk

input_audio: "/Users/silas/GitHub/whisper_streaming_web/mydata/preche.wav"

model: large-v3-turbo
 
task: transcribe
backend: mlx-whisper
min_chunk_size: 1.0
buffer_trimming_sec: 17
buffer_trimming: sentence
log_level: DEBUG



start_at: 0
model_cache_dir: null
model_dir: null
vac: false
vac_chunk_size: 0.04
vad: false
