lan: fr # source language
target_languages:
  - en
#  - de
  - uk
#  - es

warmup_file: "/Users/silas/GitHub/translation_streaming/mydata/samples_jfk.wav"
input_audio: "/Users/silas/GitHub/translation_streaming/mydata/preche.wav"
# input_audio: "mic"

#model: large-v3-turbo
model: /Users/silas/GitHub/Transcription/mlx_models/whisper-large-v3-french

task: transcribe
backend: mlx-whisper
min_chunk_size: 2.0

buffer_trimming: segment
buffer_trimming_sec: 15

# buffer_trimming: sentence
# buffer_trimming_sec: 21

log_level: DEBUG

output_dir: "translations"


start_at: 0
model_cache_dir: null
model_dir: null
vac: false
vac_chunk_size: 0.04
vad: false
