lan: fr # source language
target_languages:
  - en
  - de
  - uk

warmup_file: "/Users/silas/GitHub/whisper_streaming_web/mydata/samples_jfk.wav"
input_audio: "/Users/silas/GitHub/whisper_streaming_web/mydata/preche.wav"
#input_audio: "mic"

model: large-v3-turbo
 
task: transcribe
backend: mlx-whisper
min_chunk_size: 2.0
buffer_trimming_sec: 21
buffer_trimming: sentence
log_level: DEBUG

output_dir: "translations"


start_at: 0
model_cache_dir: null
model_dir: null
vac: false
vac_chunk_size: 0.04
vad: false
